org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=64m -XX:TieredStopAtLevel=1 -XX:+UseSerialGC -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.parallel=false
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
kotlin.compiler.execution.strategy=in-process
